### ISSUE TITLE
Update rector version

### ISSUE THREAD

**Issue by tomasnorre** [sabbelasichon/typo3-rector-testing-framework#1]
Hi,

Thanks for your awesome work, with this rector rule too. 

I think the composer.json, and perhaps some additional adjustments need to be done. 
It's mentioned as a split from TYPO3 Rector in version 2.0.0, after the release of Rector 1.0, but this still requires and older version of Rector.

Thanks in advance.

**Comment by sabbelasichon** [comment]
@tomasnorre Thanks. Make sense to adjust it in order to play nicely with the whole ecosystem.
